<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:vp4basis2026="https://wfs2-miljoegis.mim.dk/vp4basis2026" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://wfs2-miljoegis.mim.dk/vp4basis2026">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://wfs2-miljoegis.mim.dk/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="vp4_ba_26_punkt_rens_samlType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="x_koord" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="y_koord" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="vandomr_id" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="aar" nillable="true" type="xsd:short"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="komm_nr" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="komm_navn" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="pkt_id" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="mst_id" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ho_id" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="distr_id" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="link" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="pkt_type" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="pkt_navn" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ejer" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_va_sta" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_bi_sta" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_co_sta" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_tn_sta" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_tp_sta" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_va_ba" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_bi_ba" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_co_ba" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_tn_ba" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="udl_tp_ba" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dim_pe" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="godk_pe" nillable="true" type="xsd:float"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="rens_sta" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="rens_fr" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="wkb_geometry" nillable="true" type="gml:GeometryPropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="vp4_ba_26_punkt_rens_saml" substitutionGroup="gml:AbstractFeature" type="vp4basis2026:vp4_ba_26_punkt_rens_samlType"/>
</xsd:schema>
